<?php

namespace Database\Seeders;

use App\Models\PrepPartyCoalition;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PrepPartyCoalitionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currentDate= date('Y-m-d h:m:s');
        PrepPartyCoalition::insert([
            // [
            //     'prep_election_id'=> 1,
            //     'short' => 'FYC',
            //     'name' => 'FYC',
            //     'logo' => 'img/logos/fyc.jpg',
            //     'parties' => null,
            //     'is_coalition' => false,
            //     'is_independent' => false,
            //     'is_active'=> true,
            //     'created_at' => $currentDate,
            //     'updated_at' => $currentDate,
            // ],
            // [
            //     'prep_election_id'=> 1,
            //     'short' => 'MC',
            //     'name' => 'MC',
            //     'logo' => 'img/logos/mc.jpg',
            //     'parties' => null,
            //     'is_coalition' => false,
            //     'is_independent' => false,
            //     'is_active'=> true,
            //     'created_at' => $currentDate,
            //     'updated_at' => $currentDate,
            // ],
            // [
            //     'prep_election_id'=> 1,
            //     'short' => 'PAN',
            //     'name' => 'PAN',
            //     'logo' => 'img/logos/pan.jpg',
            //     'parties' => null,
            //     'is_coalition' => false,
            //     'is_independent' => false,
            //     'is_active'=> true,
            //     'created_at' => $currentDate,
            //     'updated_at' => $currentDate,
            // ],
            // [
            //     'prep_election_id'=> 1,
            //     'short' => 'PRI',
            //     'name' => 'PRI',
            //     'logo' => 'img/logos/pri.jpg',
            //     'parties' => null,
            //     'is_coalition' => false,
            //     'is_independent' => false,
            //     'is_active'=> true,
            //     'created_at' => $currentDate,
            //     'updated_at' => $currentDate,
            // ],
            // [
            //     'prep_election_id'=> 1,
            //     'short' => 'PRD',
            //     'name' => 'PRD',
            //     'logo' => 'img/logos/prd.jpg',
            //     'parties' => null,
            //     'is_coalition' => false,
            //     'is_independent' => false,
            //     'is_active'=> true,
            //     'created_at' => $currentDate,
            //     'updated_at' => $currentDate,
            // ],
            // [
            //     'prep_election_id'=> 1,
            //     'short' => 'PAN-PRI-PRD',
            //     'name' => 'PAN-PRI-PRD',
            //     'logo' => 'img/logos/pan-pri-prd.jpg',
            //     'parties' => null,
            //     'is_coalition' => true,
            //     'is_independent' => false,
            //     'is_active'=> true,
            //     'created_at' => $currentDate,
            //     'updated_at' => $currentDate,
            // ],
            // [
            //     'prep_election_id'=> 1,
            //     'short' => 'PAN-PRI',
            //     'name' => 'PAN-PRI',
            //     'logo' => 'img/logos/pan-pri.jpg',
            //     'parties' => null,
            //     'is_coalition' => true,
            //     'is_independent' => false,
            //     'is_active'=> true,
            //     'created_at' => $currentDate,
            //     'updated_at' => $currentDate,
            // ],
            // [
            //     'prep_election_id'=> 1,
            //     'short' => 'PAN-PRD',
            //     'name' => 'PAN-PRD',
            //     'logo' => 'img/logos/pan-prd.jpg',
            //     'parties' => null,
            //     'is_coalition' => true,
            //     'is_independent' => false,
            //     'is_active'=> true,
            //     'created_at' => $currentDate,
            //     'updated_at' => $currentDate,
            // ],
            // [
            //     'prep_election_id'=> 1,
            //     'short' => 'PRI-PRD',
            //     'name' => 'PRI-PRD',
            //     'logo' => 'img/logos/pri-prd.jpg',
            //     'parties' => null,
            //     'is_coalition' => true,
            //     'is_independent' => false,
            //     'is_active'=> true,
            //     'created_at' => $currentDate,
            //     'updated_at' => $currentDate,
            // ],
            [
                'prep_election_id'=> 1,
                'short' => 'Fuerza México',
                'name' => 'Fuerza México',
                'logo' => 'img/logos/fm.png',
                'parties' => null,
                'is_coalition' => false,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'Chiapas Unido',
                'name' => 'Chiapas Unido',
                'logo' => 'img/logos/chu.png',
                'parties' => null,
                'is_coalition' => false,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'Mover a Chiapas',
                'name' => 'Mover a Chiapas',
                'logo' => 'img/logos/mac.png',
                'parties' => null,
                'is_coalition' => false,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'Morena',
                'name' => 'Morena',
                'logo' => 'img/logos/mor.png',
                'parties' => null,
                'is_coalition' => false,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'Movimiento Ciudadano',
                'name' => 'Movimiento Ciudadano',
                'logo' => 'img/logos/mc.png',
                'parties' => null,
                'is_coalition' => false,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'PAN-PRI-PRD',
                'name' => 'PAN-PRI-PRD',
                'logo' => 'img/logos/pan-pri-prd.png',
                'parties' => null,
                'is_coalition' => true,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'PAN',
                'name' => 'PAN',
                'logo' => 'img/logos/pan.png',
                'parties' => null,
                'is_coalition' => false,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'PRI',
                'name' => 'PRI',
                'logo' => 'img/logos/pri.png',
                'parties' => null,
                'is_coalition' => false,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'PRD',
                'name' => 'PRD',
                'logo' => 'img/logos/prd.png',
                'parties' => null,
                'is_coalition' => false,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'PAN-PRI',
                'name' => 'PAN-PRI',
                'logo' => 'img/logos/pan-pri.png',
                'parties' => null,
                'is_coalition' => true,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'PAN-PRD',
                'name' => 'PAN-PRD',
                'logo' => 'img/logos/pan-prd.png',
                'parties' => null,
                'is_coalition' => true,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'PRI-PRD',
                'name' => 'PRI-PRD',
                'logo' => 'img/logos/pri-prd.png',
                'parties' => null,
                'is_coalition' => true,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'PES',
                'name' => 'PES',
                'logo' => 'img/logos/pes.png',
                'parties' => null,
                'is_coalition' => false,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'PT',
                'name' => 'PT',
                'logo' => 'img/logos/pt.png',
                'parties' => null,
                'is_coalition' => false,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'Verde',
                'name' => 'Verde',
                'logo' => 'img/logos/verde.png',
                'parties' => null,
                'is_coalition' => false,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'RSP',
                'name' => 'RSP',
                'logo' => 'img/logos/rsp.png',
                'parties' => null,
                'is_coalition' => false,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'Candidatura no registrada',
                'name' => 'Candidatura no registrada',
                'logo' => null,
                'parties' => null,
                'is_coalition' => false,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
            [
                'prep_election_id'=> 1,
                'short' => 'Votos nulos',
                'name' => 'Votos nulos',
                'logo' => null,
                'parties' => null,
                'is_coalition' => false,
                'is_independent' => false,
                'is_active'=> true,
                'created_at' => $currentDate,
                'updated_at' => $currentDate,
            ],
        ]);
    }
}
